#!/bin/sh
if [ $# -lt 2 ]; then
	echo "usage: $0 local-host remote-host [options]"
	echo "  All options are passed directly to tcpserver."
	exit 1
fi
prefix=`dirname $0`
localhost=$1
PROXY_CONNECT_HOST=$2
export PROXY_CONNECT_HOST
shift 2
exec \
envuidgid nobody \
tcpserver -HRUllocalhost "$@" $localhost 110 \
$prefix/ucspi-proxy-pop3 \
/usr/sbin/relay-ctrl-allow /bin/true
