.TH ucspi-proxy-http-xlate 1
.SH NAME
ucspi-proxy-http-xlate \- Translating HTTP proxy
.SH SYNOPSIS
.B ucspi-proxy-http-xlate
[
.B -v
]
.I search replace [ search replace [...]]
.SH DESCRIPTION
.B ucspi-proxy-http-xlate
is a HTTP proxy for a UCSPI client/server pair that can translate
strings within HTTP content on the fly.
All occurrences of
.I search
are replaced with
.IR replace .
If the HTTP response from the server contained a
.B Content-Length
header, it is replaced with the length of the translated content.
.SH SEE ALSO
ucspi-proxy(1)
.SH CAVEATS
All content is translated.
This could cause some odd side-effects if a search string is found in a
binary response, such as an image.
